// <auto-generated />

using System;
using Adin.BankPayment.Domain.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Adin.BankPayment.Domain.Migrations
{
    [DbContext(typeof(BankPaymentContext))]
    internal class BankPaymentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Adin.BankPayment.Domain.Model.Application", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<int>("CreatedBy");

                b.Property<DateTime>("CreationDate");

                b.Property<string>("Description")
                    .HasMaxLength(256);

                b.Property<bool>("IsDeleted")
                    .ValueGeneratedOnAdd()
                    .HasDefaultValue(false);

                b.Property<int?>("ModifiedBy");

                b.Property<DateTime?>("ModifiedOn");

                b.Property<string>("PrivateKey")
                    .HasMaxLength(128);

                b.Property<string>("PublicKey")
                    .HasMaxLength(128);

                b.Property<byte[]>("RowVersion")
                    .IsConcurrencyToken()
                    .ValueGeneratedOnAddOrUpdate();

                b.Property<byte>("Status");

                b.Property<string>("Title")
                    .HasMaxLength(32);

                b.HasKey("Id");

                b.ToTable("Application");
            });

            modelBuilder.Entity("Adin.BankPayment.Domain.Model.ApplicationBank", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<Guid>("ApplicationId");

                b.Property<Guid>("BankId");

                b.Property<int>("CreatedBy");

                b.Property<DateTime>("CreationDate");

                b.Property<bool>("IsDeleted")
                    .ValueGeneratedOnAdd()
                    .HasDefaultValue(false);

                b.Property<int?>("ModifiedBy");

                b.Property<DateTime?>("ModifiedOn");

                b.Property<byte[]>("RowVersion")
                    .IsConcurrencyToken()
                    .ValueGeneratedOnAddOrUpdate();

                b.Property<byte>("Status");

                b.HasKey("Id");

                b.HasIndex("ApplicationId");

                b.HasIndex("BankId");

                b.ToTable("ApplicationBank");
            });

            modelBuilder.Entity("Adin.BankPayment.Domain.Model.ApplicationBankParam", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<Guid>("ApplicationBankId");

                b.Property<int>("CreatedBy");

                b.Property<DateTime>("CreationDate");

                b.Property<bool>("IsDeleted")
                    .ValueGeneratedOnAdd()
                    .HasDefaultValue(false);

                b.Property<int?>("ModifiedBy");

                b.Property<DateTime?>("ModifiedOn");

                b.Property<string>("ParamKey")
                    .HasMaxLength(32);

                b.Property<string>("ParamValue")
                    .HasMaxLength(128);

                b.Property<byte[]>("RowVersion")
                    .IsConcurrencyToken()
                    .ValueGeneratedOnAddOrUpdate();

                b.Property<byte>("Status");

                b.HasKey("Id");

                b.HasIndex("ApplicationBankId");

                b.ToTable("ApplicationBankParam");
            });

            modelBuilder.Entity("Adin.BankPayment.Domain.Model.Bank", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<byte>("Code");

                b.Property<int>("CreatedBy");

                b.Property<DateTime>("CreationDate");

                b.Property<bool>("IsDeleted")
                    .ValueGeneratedOnAdd()
                    .HasDefaultValue(false);

                b.Property<int?>("ModifiedBy");

                b.Property<DateTime?>("ModifiedOn");

                b.Property<string>("PostUrl")
                    .HasMaxLength(64);

                b.Property<byte[]>("RowVersion")
                    .IsConcurrencyToken()
                    .ValueGeneratedOnAddOrUpdate();

                b.Property<byte>("Status");

                b.Property<string>("Title")
                    .HasMaxLength(16);

                b.HasKey("Id");

                b.ToTable("Bank");

                b.HasData(
                    new
                    {
                        Id = new Guid("482a591e-7536-4f47-a544-e9d4342586bd"),
                        Code = (byte)1,
                        CreatedBy = 1,
                        CreationDate = new DateTime(2018, 8, 6, 19, 24, 49, 523, DateTimeKind.Local),
                        IsDeleted = false,
                        PostUrl = "https://sep.shaparak.ir/MobilePG/MobilePayment",
                        Status = (byte)0,
                        Title = "سامان"
                    },
                    new
                    {
                        Id = new Guid("ab3f226a-be56-4092-bbd0-2ae8ffbce131"),
                        Code = (byte)2,
                        CreatedBy = 1,
                        CreationDate = new DateTime(2018, 8, 6, 19, 24, 49, 525, DateTimeKind.Local),
                        IsDeleted = false,
                        PostUrl = "https://pec.shaparak.ir/pecpaymentgateway/default.aspx?au={0}",
                        Status = (byte)0,
                        Title = "پارسیان"
                    },
                    new
                    {
                        Id = new Guid("98504148-3d89-4abb-9fb5-281bed8714e3"),
                        Code = (byte)3,
                        CreatedBy = 1,
                        CreationDate = new DateTime(2018, 8, 6, 19, 24, 49, 525, DateTimeKind.Local),
                        IsDeleted = false,
                        PostUrl = "https://bpm.shaparak.ir/pgwchannel/startpay.mellat",
                        Status = (byte)0,
                        Title = "ملت"
                    },
                    new
                    {
                        Id = new Guid("e8d935f6-1c3d-4e4c-a74a-e2a569671197"),
                        Code = (byte)4,
                        CreatedBy = 1,
                        CreationDate = new DateTime(2020, 8, 6, 19, 24, 49, 525, DateTimeKind.Local),
                        IsDeleted = false,
                        PostUrl = "https://pf.efarda.ir/pf/api/ipg/purchase",
                        Status = (byte)0,
                        Title = "ارتباط فردا"
                    },
                    new
                    {
                        Id = new Guid("e147830f-696d-4c4a-a7b4-b20722dd3ff6"),
                        Code = (byte)5,
                        CreatedBy = 1,
                        CreationDate = new DateTime(2020, 8, 6, 19, 24, 49, 525, DateTimeKind.Local),
                        IsDeleted = false,
                        PostUrl = "https://pep.shaparak.ir/payment.aspx",
                        Status = (byte)0,
                        Title = "پاسارگاد"
                    }                    
                );
            });

            modelBuilder.Entity("Adin.BankPayment.Domain.Model.Transaction", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<decimal>("Amount");

                b.Property<Guid>("ApplicationId");

                b.Property<int>("BankErrorCode");

                b.Property<string>("BankErrorMessage")
                    .HasMaxLength(64);

                b.Property<Guid>("BankId");

                b.Property<string>("BankRedirectUrl")
                    .HasMaxLength(128);

                b.Property<string>("BankTrackCode")
                    .HasMaxLength(64);

                b.Property<string>("CallbackUrl")
                    .HasMaxLength(128);

                b.Property<int>("CreatedBy");

                b.Property<DateTime>("CreationDate");

                b.Property<byte>("ErrorCode");

                b.Property<DateTime?>("ExpirationTime");

                b.Property<bool>("IsDeleted")
                    .ValueGeneratedOnAdd()
                    .HasDefaultValue(false);

                b.Property<long?>("Mobile");

                b.Property<int?>("ModifiedBy");

                b.Property<DateTime?>("ModifiedOn");

                b.Property<string>("ReferenceNumber")
                    .HasMaxLength(64);

                b.Property<byte[]>("RowVersion")
                    .IsConcurrencyToken()
                    .ValueGeneratedOnAddOrUpdate();

                b.Property<byte>("Status");

                b.Property<string>("UserTrackCode")
                    .HasMaxLength(64);

                b.HasKey("Id");

                b.HasIndex("ApplicationId");

                b.HasIndex("BankId");

                b.ToTable("Transaction");
            });

            modelBuilder.Entity("Adin.BankPayment.Domain.Model.ApplicationBank", b =>
            {
                b.HasOne("Adin.BankPayment.Domain.Model.Application", "Application")
                    .WithMany()
                    .HasForeignKey("ApplicationId")
                    .OnDelete(DeleteBehavior.Cascade);

                b.HasOne("Adin.BankPayment.Domain.Model.Bank", "Bank")
                    .WithMany()
                    .HasForeignKey("BankId")
                    .OnDelete(DeleteBehavior.Cascade);
            });

            modelBuilder.Entity("Adin.BankPayment.Domain.Model.ApplicationBankParam", b =>
            {
                b.HasOne("Adin.BankPayment.Domain.Model.ApplicationBank", "ApplicationBank")
                    .WithMany("ApplicationBankParams")
                    .HasForeignKey("ApplicationBankId")
                    .OnDelete(DeleteBehavior.Cascade);
            });

            modelBuilder.Entity("Adin.BankPayment.Domain.Model.Transaction", b =>
            {
                b.HasOne("Adin.BankPayment.Domain.Model.Application", "Application")
                    .WithMany()
                    .HasForeignKey("ApplicationId")
                    .OnDelete(DeleteBehavior.Cascade);

                b.HasOne("Adin.BankPayment.Domain.Model.Bank", "Bank")
                    .WithMany()
                    .HasForeignKey("BankId")
                    .OnDelete(DeleteBehavior.Cascade);
            });
#pragma warning restore 612, 618
        }
    }
}